### ISSUE TITLE
Scroll arrow needs to be visible 

### ISSUE THREAD

**Issue by pablitod123** [hydrosquall/yudi-site#1]
This is the scroll arrow for the homepage - it's just off the bottom of the page

**Comment by hydrosquall** [comment]
This is a screen sizing issue that goes beyond just browser version- I'll let him know.

**Comment by hydrosquall** [comment]
Steve has signaled it's OK to drop this completely- will leave it in for now in case new sections get added to the front later, but removing the arrow will also justify removing a bunch of scripts from the site footer area.
