### ISSUE TITLE
Fix extra space on the right side  (Safari only) 

### ISSUE THREAD

**Issue by pablitod123** [hydrosquall/yudi-site#2]
Some derpy css glitch with the navbar where Safari is being silly, probably

**Comment by hydrosquall** [comment]
We'll deal with this last

**Comment by hydrosquall** [comment]
scratch that, didn't realize the page was actually getting wider: maybe something like this is going on

http://stackoverflow.com/questions/10486115/google-chrome-and-safari-my-website-gives-extra-space-on-the-right-side

**Comment by hydrosquall** [comment]
@pablitod123 If you have time to tackle this one more thing- great! If not- Otherwise- I'll handle the contacts thing later and you're all done :)

**Comment by pablitod123** [comment]
I'll take a look and let you know! Will need to stop in just a bit for today but I can return to it tomorrow as well. I feel like I've approached this before at some point so there's hope yet.

**Comment by hydrosquall** [comment]
sweet. since this is a more intensive fix than the others, I'd advise pushing the commits to an alternate branch rather than master.

**Comment by pablitod123** [comment]
Got it! Unfortunately I'm a noob with condensing css so I don't want to mess with the .min file, but we needed to add {overflow-x:hidden} to BOTH the body and html tags. Sorry the picture is horrendously confusing, and let me know if this anything is weird about doing this for some reason. 
![screen shot 2015-08-20 at 5 06 22 pm](https://cloud.githubusercontent.com/assets/7172273/9388512/dff3dbb0-475d-11e5-8a38-44b21b5d047e.png)

If you want to add that to the css file that'd be sweet. I'm happy to do it, just don't want to mess with any condensed css magic.

**Comment by hydrosquall** [comment]
Dude, that's awesome! I'll try it out and see what happens

**Comment by hydrosquall** [comment]
How's it look? Just pushed it live

Addressed in commit
https://github.com/hydrosquall/yudi-site/commit/41e76e5e7109b31a5615cc15e62a572bffc8412e

**Comment by pablitod123** [comment]
No more weird white space! It's weird though, "Application" didn't change to "Compete" (maybe I missed something) and none of the other things seem to have updated. You haven't tried pushing the other updates yet I hope?

**Comment by hydrosquall** [comment]
I had only pushed the new css to the server which is why that issue is gone now. Just uploaded your changes to `donate.html` and `index.html` so that should be taken care of now!
