### ISSUE TITLE
Team page - replace names

### ISSUE THREAD

**Issue by pablitod123** [hydrosquall/yudi-site#3]

**Comment by hydrosquall** [comment]
![image](https://cloud.githubusercontent.com/assets/9020979/9386781/27955d6e-472b-11e5-8b10-8e06a6d29972.png)

**Comment by hydrosquall** [comment]
Complete as of this commit: 

https://github.com/hydrosquall/yudi-site/commit/094076509f8922bfb6fccca6cb3f2685d03ff34e
