### ISSUE TITLE
Donate Page - text changes

### ISSUE THREAD

**Issue by pablitod123** [hydrosquall/yudi-site#4]
Nice n easy

**Comment by hydrosquall** [comment]
![image](https://cloud.githubusercontent.com/assets/9020979/9386828/624dcd88-472b-11e5-841f-03aef63d40bf.png)

A little odd that the left 2 items are left aligned but the 3rd one he wants centered- ah well

**Comment by pablitod123** [comment]
Made the text changes, we'll see how the alignment works out

**Comment by hydrosquall** [comment]
Address in this commit:  bb323e1c1836715c06bc3cfa10f41b990153a777

If alignment needs to change, I think one can just change the text-align property for the `donate__box` class selector that I defined when refactoring the site last month.
