### ISSUE TITLE
Improve image quality of bios/contact page

### ISSUE THREAD

**Issue by pablitod123** [hydrosquall/yudi-site#6]
Not sure if there's a better way to do this than to just use better pictures.

**Comment by hydrosquall** [comment]
Yep, there isn't anything we can do about it. I can sort of see blurriness on the contact page but otherwise the bio pictures are reasonably sharp.

**Comment by pablitod123** [comment]
I'm about to email you a higher quality version of the photograph, since I can seem to find a way to replace the existing "contact.jpg" from github.

**Comment by hydrosquall** [comment]
swapped it- make sure to do a git pull before pushing anything new
